<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchUsers($search_by){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $result = $qb->select('u.username')
                    ->addSelect('u.email')
                    ->from("AppBundle:User", 'u')
                    ->where($qb->expr()->like('u.username', ':search'))
                    ->orWhere($qb->expr()->like('u.email', ':search'))
                    ->setParameter('search', '%'.$search_by.'%')
                    ->getQuery()
                    ->getResult();
        return $result;
    }

    public function allUsers(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $result = $qb->select('u.username')
                    ->addSelect('u.email')
                    ->from("AppBundle:User", 'u')
                    ->getQuery()
                    ->getResult();
        return $result;
    }
}
